[
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [ 99 ],
    id: 900901,
    title: 'Ironman',
    original_language: 'bn',
    original_title: 'Ironman',
    overview: "'Ironman Arafat', ran 1004 kilometers from Teknaf to Tetulia in 20 days, swam the Bengali Channel 6 times, completed the world's toughest one-day Ironman Triathlon Challenge three times, and became the first Bangladeshi to win the 'Ironman 70.3 World Championship'.",
    popularity: 0.1411,
    poster_path: '/pnLopkBeVGd0v77gpTNdPqQESUs.jpg',
    release_date: '2021-11-21',
    softcore: false,
    video: false,
    vote_average: 7.5,
    vote_count: 1
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [ 878 ],
    id: 1557516,
    title: 'Ironman',
    original_language: 'et',
    original_title: 'Ironman',
    overview: 'The science fiction film takes place in historically recognizable places in Valga. During the shooting, local militias also had to be dealt with. The robot misleads gangsters-bank robbers. But who is he and who is his master?',
    popularity: 0.1014,
    poster_path: null,
    release_date: '1987-01-01',
    softcore: false,
    video: false,
    vote_average: 0,
    vote_count: 0
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [ 99 ],
    id: 890373,
    title: 'Ironman',
    original_language: 'mk',
    original_title: 'Железен човек',
    overview: 'Vojo, a retired police officer lives in Skopje, one of the most polluted cities in the world. He finds meaning in his passion and love for innovation, which he directs towards clean energy and ecology. Over the past 15 years, he has successfully implemented eight patented projects, but his passion is reserved for building a perpetual motion machine that will generate clean electricity without the need for an energy source. Will our Don Quixote-like hero succeed in fulfilling his mission – reducing pollution to save Earth from global warming and destruction by man – or will he redeem himself for the damage his obsession has caused to his family?',
    popularity: 0.0071,
    poster_path: null,
    release_date: '',
    softcore: false,
    video: false,
    vote_average: 0,
    vote_count: 0
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 1377523,
    title: 'Wild Man to Ironman',
    original_language: 'en',
    original_title: 'Wild Man to Ironman',
    overview: "Wales's ex party boy Mat Pritchard has cleaned up his life and turned to ultra-endurance. He takes on his biggest endurance challenge yet, to be the first person to swim, cycle, and run around Wales, in just 14 days.",
    popularity: 0.1469,
    poster_path: '/rzNrPSU3UE3O1ixrhCsrjXn8lFi.jpg',
    release_date: '2018-12-19',
    softcore: false,
    video: false,
    vote_average: 5,
    vote_count: 1
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [ 28, 878, 10751, 35 ],
    id: 938847,
    title: 'Space Ironman Kyodain: The Movie',
    original_language: 'ja',
    original_title: '宇宙鉄人キョーダイン',
    overview: 'Captured by an alien empire from the planet Dada, Dr. Hayama has programmed the personalities of his two kidnapped sons, Joji and Ryuji, into two Cyberroids to combat the Dada Robot Army and care for his youngest son, Kenji.',
    popularity: 0.5427,
    poster_path: '/8WRbicL2lcnzpJuyXvvfoO1xlMu.jpg',
    release_date: '1976-07-18',
    softcore: false,
    video: false,
    vote_average: 5.5,
    vote_count: 1
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [ 28, 12, 99 ],
    id: 1427600,
    title: 'The Road To Ironman',
    original_language: 'en',
    original_title: 'The Road To Ironman',
    overview: "The Road To Ironman follows Mauritz Eklund's inspiring journey as he prepares for an Ironman 70.3 triathlon. Throughout the series, Mauritz shares his motivations, training regimen, and the physical and mental challenges he faces. Each episode offers a glimpse into the dedication and perseverance required to achieve this monumental goal, capturing the highs and lows of his preparation. From intense workouts to moments of self-reflection, the series provides an authentic and motivating look at what it takes to become an Ironman.",
    popularity: 0.0902,
    poster_path: null,
    release_date: '',
    softcore: false,
    video: true,
    vote_average: 5.5,
    vote_count: 1
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [ 99 ],
    id: 1231073,
    title: '2023 IRONMAN World Championship Documentary',
    original_language: 'en',
    original_title: '2023 IRONMAN World Championship Documentary',
    overview: 'Since its inception in 1978, the IRONMAN World Championship has demonstrated not only the unrivaled physical ability and enduring drive of the top endurance athletes in the world but also some of the most impactful stories from the age-group athletes who compete alongside them. In 1991, IRONMAN began to package these stories into a documentary format, which has aired on broadcast television and streaming services every year since. This year’s IRONMAN World Championship special is no different. 2023 will chronicle one of triathlon’s pinnacle events, which, for the first time in the iconic event’s 45-year history, was hosted in two separate locations: the men in Nice, France, and the women in Kona, Hawaii.',
    popularity: 0.1989,
    poster_path: '/e60wBBgd9D2IZz0qgvoYmXVoZKR.jpg',
    release_date: '',
    softcore: false,
    video: false,
    vote_average: 7,
    vote_count: 1
  },
  {
    adult: false,
    backdrop_path: '/ddk9RsNasfkmzmAyDEezvUk1HEg.jpg',
    genre_ids: [ 18, 99 ],
    id: 10505,
    title: 'Run for Your Life!',
    original_language: 'de',
    original_title: 'Lauf um Dein Leben - Vom Junkie zum Ironman',
    overview: "He lived the junkie's life as a heroin addict. Triathlon transformed him. Biopic of the record breaking Ironman Andreas Niedrig.",
    popularity: 0.3112,
    poster_path: '/M7nCUXO0ktZSggHcB1blaiuezc.jpg',
    release_date: '2008-04-24',
    softcore: false,
    video: false,
    vote_average: 4.909,
    vote_count: 11
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [ 10749, 35 ],
    id: 1108477,
    title: 'IRONMAN THE SERIES 0',
    original_language: 'th',
    original_title: 'มัธยมหัวใจเหล็ก : มายแฟน - แฮนด์ซั่ม',
    overview: 'What will happen when "Rita", a rich girl, has to flirt with "Denchai", a Mower?',
    popularity: 0.0286,
    poster_path: '/hr7C7zj7ciQAp0AgIhp6xNCuORc.jpg',
    release_date: '2023-04-02',
    softcore: false,
    video: false,
    vote_average: 10,
    vote_count: 1
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [ 99 ],
    id: 920775,
    title: "Cal Ripken Jr - The Ironman's Legendary Career",
    original_language: 'en',
    original_title: "Cal Ripken Jr - The Ironman's Legendary Career",
    overview: "One of baseball's legends, Cal Ripken Jr., is chronicled in this illuminating documentary. Known for enjoying one of the longest careers in baseball history--21 years--Ripken Jr. has set records for fewest errors by a shortstop and highest fielding percentage. Of the numerous accolades that have been heaped on the player, his 2 MVP titles and election to the All-Century Team stand out. All of these career highlights, and many more, are explored in THE IRONMAN'S LEGENDARY CAREER.",
    popularity: 0.0918,
    poster_path: '/mbrVf4ILu586smI08ln7oQAVxms.jpg',
    release_date: '2001-12-18',
    softcore: false,
    video: false,
    vote_average: 6.5,
    vote_count: 1
  },
  {
    adult: false,
    backdrop_path: '/6eMSA6n3HPmzCOe0N5WyXCyKHpC.jpg',
    genre_ids: [ 28, 12, 18 ],
    id: 1203100,
    title: 'Darasingh',
    original_language: 'hi',
    original_title: 'डरा सिंह',
    overview: 'A poor wood-cutter is rewarded with a gold, but the rejected ruler abducts his mother for ransom.',
    popularity: 0.1622,
    poster_path: '/1CJRDANi2wm1ew4ybp4ordprAO4.jpg',
    release_date: '1964-01-01',
    softcore: false,
    video: false,
    vote_average: 6.5,
    vote_count: 2
  },
  {
    adult: false,
    backdrop_path: '/7yTxblK0mLcRGswkvn2UnnleUs3.jpg',
    genre_ids: [ 18, 36 ],
    id: 470360,
    title: 'Breaking the Limits',
    original_language: 'pl',
    original_title: 'Najlepszy',
    overview: 'Based on true events. In 1980s Poland, Jerzy Górski is a young man who finds the determination to struggle against his drug addiction through athletic training, with the aim of competing in the US Ironman Triathlon.',
    popularity: 1.161,
    poster_path: '/b9ZwoLW1sD2DST53lAQAE8Fog0a.jpg',
    release_date: '2017-11-17',
    softcore: false,
    video: false,
    vote_average: 7.553,
    vote_count: 104
  },
  {
    adult: false,
    backdrop_path: '/xt75NSIlfzwPwuBsuarB3i1mBxj.jpg',
    genre_ids: [ 27, 878 ],
    id: 41428,
    title: 'Tetsuo: The Iron Man',
    original_language: 'ja',
    original_title: '鉄男',
    overview: `A "metal fetishist", driven mad by the maggots wriggling in the wound he's made to embed metal into his flesh, runs out into the night and is accidentally run down by a Japanese businessman and his girlfriend. The pair dispose of the corpse in hopes of quietly moving on with their lives. However, the businessman soon finds that he is now plagued by a vicious curse that transforms his flesh into iron.`,
    popularity: 3.0075,
    poster_path: '/skAxIP1DgnVIXaUaPFozWXtsbhs.jpg',
    release_date: '1989-07-01',
    softcore: false,
    video: false,
    vote_average: 6.975,
    vote_count: 706
  },
  {
    adult: false,
    backdrop_path: '/cajuOZQyYLoL7m18YE5HbGsBt0N.jpg',
    genre_ids: [ 18 ],
    id: 471645,
    title: 'Jakoman and Tetsu',
    original_language: 'ja',
    original_title: 'ジャコ萬と鉄',
    overview: 'In a village subsisting on its herring fishery, a one-eyed criminal named Jakoman terrorizes the inhabitants. One of them, the son of the head of one of the fish companies by the name of Tetsu, decides to overthrow Jakoman and his cohorts.',
    popularity: 0.369,
    poster_path: '/4fmQx4NyqiRr0uyu9GHBxiiE2g7.jpg',
    release_date: '1964-02-08',
    softcore: false,
    video: false,
    vote_average: 7.333,
    vote_count: 3
  },
  {
    adult: false,
    backdrop_path: '/edY7dfMuQwxtTZnSdpeEGfdZS6r.jpg',
    genre_ids: [ 28, 53 ],
    id: 30526,
    title: 'Pentathlon',
    original_language: 'en',
    original_title: 'Pentathlon',
    overview: "When East German Eric Brogar wins a gold medal in the pentathlon, he escapes to freedom in the west with the help of a beautiful American athlete. But his demanding coach, Heinrich Mueller vows revenge and Eric's best friend and his father pay the ultimate price for his freedom when they are killed by the Secret Police. In Los Angeles, Eric starts to train for the gold again. But when Mueller comes to America, Eric must win the most deadly game of all… the fight for his life.",
    popularity: 0.5486,
    poster_path: '/kD5SvLTd1MSvuwPrshoIaGIDlgC.jpg',
    release_date: '1994-06-04',
    softcore: false,
    video: false,
    vote_average: 4.4,
    vote_count: 51
  }
]